In [11]:
import pandas as pd
import numpy as np

In [12]:
Hrt_atk = pd.read_csv('Heart.csv')

In [13]:
Hrt_atk.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [14]:
Hrt_atk.tail()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0

In [15]:
Hrt_atk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [16]:
len(Hrt_atk['ChestPainType'].unique())
Hrt_atk['ChestPainType'].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [17]:
Hrt_atk[Hrt_atk['ChestPainType']=='ATA']

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
2     37   M           ATA        130          283          0         ST   
6     45   F           ATA        130          237          0     Normal   
7     54   M           ATA        110          208          0     Normal   
9     48   F           ATA        120          284          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
903   56   M           ATA        130          221          0        LVH   
904   56   M           ATA        120          240          0     Normal   
906   55   F           ATA        132          342          0     Normal   
910   41   M           ATA        120          157          0     Normal   
916   57   F           ATA        130          236          0        LVH   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
2       98              N      0.0       Up             0  
6      170              N      0.0       Up             0  
7      142              N      0.0       Up             0  
9      120              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
903    163              N      0.0       Up             0  
904    169              N      0.0     Down             0  
906    166              N      1.2       Up             0  
910    182              N      0.0       Up             0  
916    174              N      0.0     Flat             1  

[173 rows x 12 columns]

In [18]:
y = pd.get_dummies(Hrt_atk.ChestPainType, prefix='ChestPainType')


In [19]:
y.head()

ChestPainType_ASY  ChestPainType_ATA  ChestPainType_NAP  ChestPainType_TA
0                  0                  1                  0                 0
1                  0                  0                  1                 0
2                  0                  1                  0                 0
3                  1                  0                  0                 0
4                  0                  0                  1                 0

In [20]:
len(Hrt_atk['RestingECG'].unique())


3

In [21]:
x = pd.get_dummies(Hrt_atk.RestingECG, prefix='RestingECG')


In [22]:
x.head()

RestingECG_LVH  RestingECG_Normal  RestingECG_ST
0               0                  1              0
1               0                  1              0
2               0                  0              1
3               0                  1              0
4               0                  1              0

In [23]:
len(Hrt_atk['ExerciseAngina'].unique())


2

In [24]:
Hrt_atk['ExerciseAngina'].unique()


array(['N', 'Y'], dtype=object)

In [25]:
Hrt_atk['ExerciseAngina'] = Hrt_atk['ExerciseAngina'].map({'Y': 1, 'N': 0})


In [26]:
Hrt_atk['ExerciseAngina'].unique()


array([0, 1])

In [27]:
Hrt_atk['Sex'].unique()


array(['M', 'F'], dtype=object)

In [28]:
Hrt_atk['Sex'] = Hrt_atk['Sex'].map({'M': 1, 'F': 0})


In [29]:
Hrt_atk['Sex'].unique()


array([1, 0])

In [30]:
len(Hrt_atk['ST_Slope'].unique())


3

In [31]:
Hrt_atk['ST_Slope'].unique()


array(['Up', 'Flat', 'Down'], dtype=object)

In [32]:
Hrt_atk['ST_Slope'] = Hrt_atk['ST_Slope'].map({'Up': 1, 'Down': 0 , 'Flat': 2 })


In [33]:
Hrt_atk['ST_Slope'].unique()


array([1, 2, 0])

In [34]:
Hrt_atk = Hrt_atk.drop(['ChestPainType', 'RestingECG'], axis=1)


In [35]:
final_df = pd.concat([Hrt_atk, x,y], axis=1)

In [36]:
final_df.head()

Age  Sex  RestingBP  Cholesterol  FastingBS  MaxHR  ExerciseAngina  \
0   40    1        140          289          0    172               0   
1   49    0        160          180          0    156               0   
2   37    1        130          283          0     98               0   
3   48    0        138          214          0    108               1   
4   54    1        150          195          0    122               0   

   Oldpeak  ST_Slope  HeartDisease  RestingECG_LVH  RestingECG_Normal  \
0      0.0         1             0               0                  1   
1      1.0         2             1               0                  1   
2      0.0         1             0               0                  0   
3      1.5         2             1               0                  1   
4      0.0         1             0               0                  1   

   RestingECG_ST  ChestPainType_ASY  ChestPainType_ATA  ChestPainType_NAP  \
0              0                  0                  1                  0   
1              0                  0                  0                  1   
2              1                  0                  1                  0   
3              0                  1                  0                  0   
4              0                  0                  0                  1   

   ChestPainType_TA  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0

In [37]:
final_df.shape

(918, 17)

In [38]:
final_df[final_df['HeartDisease']==0].shape

(410, 17)

In [39]:
final_df[final_df['HeartDisease']==1].shape

(508, 17)

In [40]:
!pip install imbalanced-learn

In [41]:
from imblearn.over_sampling import SMOTE

In [42]:
from sklearn.model_selection import train_test_split


X = final_df.drop('HeartDisease', axis=1)
y= final_df['HeartDisease']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=100)

In [43]:
up_sampler = SMOTE(random_state = 50)

X_up,y_up = up_sampler.fit_resample(X,y)

print('post upsampling :')
y_up.value_counts(normalize=True) *100 

post upsampling :


0    50.0
1    50.0
Name: HeartDisease, dtype: float64

In [44]:
X_train,X_test,y_train,y_test = train_test_split(X_up, y_up, test_size = 0.25, random_state = 100)

In [45]:
# Model_1

In [66]:
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression()

log_model.fit(X_train, y_train)

predictions = log_model.predict(X_test)


prediction_score = log_model.score(X_test, y_test)
print('The accuracy score is :', prediction_score)

The accuracy score is : 0.8622047244094488


/Users/sohelsalam/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [67]:
from sklearn import metrics

confidence_matrix = metrics.confusion_matrix(y_test , predictions)

In [68]:
print(confidence_matrix)

[[113  18]
 [ 17 106]]


In [70]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.87      0.86      0.87       131
           1       0.85      0.86      0.86       123

    accuracy                           0.86       254
   macro avg       0.86      0.86      0.86       254
weighted avg       0.86      0.86      0.86       254



In [81]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [82]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8858267716535433


In [83]:
from sklearn import metrics

confidence_matrix = metrics.confusion_matrix(y_test , y_pred)

In [84]:
print(confidence_matrix)

[[114  17]
 [ 12 111]]


In [85]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.87      0.89       131
           1       0.87      0.90      0.88       123

    accuracy                           0.89       254
   macro avg       0.89      0.89      0.89       254
weighted avg       0.89      0.89      0.89       254



In [76]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [77]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8740157480314961


In [78]:
from sklearn import metrics

confidence_matrix = metrics.confusion_matrix(y_test , y_pred)

In [79]:
print(confidence_matrix)

[[111  20]
 [ 12 111]]


In [80]:
from sklearn.metrics import confusion_matrix,classification_report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.85      0.87       131
           1       0.85      0.90      0.87       123

    accuracy                           0.87       254
   macro avg       0.87      0.87      0.87       254
weighted avg       0.88      0.87      0.87       254

